# Generated by Django 4.1.7 on 2023-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_actor_comment_director_slug_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
